language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CI_HOME=`pwd`/src
node_js:
  - "v5.7.0"
before_install:
  - cd src
after_install:
  - npm install
script:
  - bin/mocha

