node:
  image: node:5.7-wheezy
  container_name: ${DOCKER_CONTAINER_PREFIX}_node
  command: tail -f /dev/null
  working_dir: /opt/tinifyd
  env_file: ./src/.env
  links:
    - db
  volumes_from:
    - storage

db:
  image: percona:5.6
  container_name: ${DOCKER_CONTAINER_PREFIX}_db
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: ${TINIFYD_DB_PASS}
    MYSQL_DATABASE: ${TINIFYD_DB_NAME}
  env_file: ./src/.env
  volumes_from:
    - storage

storage:
  image: busybox:latest
  container_name: ${DOCKER_CONTAINER_PREFIX}_storage
  volumes:
    - /opt/tinifyd
    - ./src:/opt/tinifyd

    - ${TINIFYD_SOURCE_PATH}:/var/lib/tinifyd/images
    - ${TINIFYD_TEMP_PATH}:/tmp/tinifyd
    - ./var/log/pm2:/var/log/pm2
    - ./var/log/mysql:/var/log/mysql
    - ./var/lib/mysql:/var/lib/mysql
    #- ./env/db/etc/mysql:/etc/mysql

