${PROJECT}_node:
  image: node:6.4.0-wheezy
  container_name: ${PROJECT}_node
  command: tail -f /dev/null
  working_dir: /opt/tinifyd
  env_file: .env
  environment:
    TINIFYD_DB_HOST: ${PROJECT}_db
  links:
    - ${PROJECT}_db
  volumes_from:
    - ${PROJECT}_storage

${PROJECT}_db:
  image: percona:5.7
  container_name: ${PROJECT}_db
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: ${TINIFYD_DB_PASS}
    MYSQL_DATABASE: ${TINIFYD_DB_NAME}
  env_file: .env
  volumes_from:
    - ${PROJECT}_storage

${PROJECT}_storage:
  image: busybox:latest
  container_name: ${PROJECT}_storage
  volumes:
    - ./src:/opt/tinifyd
    - ${TINIFYD_SOURCE_PATH}:/var/lib/tinifyd/images
    - ${TINIFYD_BACKUP_PATH}:/var/lib/tinifyd/originals
    - ${TINIFYD_TEMP_PATH}:/tmp/tinifyd
    - ${TINIFYD_DB_DATA_VOLUME}:/var/lib/mysql
    - ./var/log/pm2:/var/log/pm2
    - ./var/log/mysql:/var/log/mysql

