#!/usr/bin/env bash

$NODE_CONTAINER=tinifyd_node
$DB_CONTAINER=tinifyd_db

docker exec 

node --harmony src/node_modules/db-migrate/bin/db-migrate \
    --env=default \
    --config=./src/database/config.json \
    --migrations-dir=./src/database/migrations \
    $*
